# SPDX-FileCopyrightText: 2026 Vedran Lebo <vedran@flyingpenguin.tech>
# SPDX-License-Identifier: MIT
version: "2"

linters:
  default: standard
  disable:
    - errcheck  # Too noisy for print functions, Close(), Signal() etc.
